@startuml
start
:Врач выбирает пациента;
:Врач выбирает препарат;
:Вводит дозировку, время и период;
if (Данные корректны?) then (да)
  :Сохранить назначение;
  :Сформировать расписание;
  :Назначение доступно пациенту;
else (нет)
  :Показать ошибку;
  :Исправить данные;
endif
stop
@enduml

